// Curated list of location tokens Fantastic Jobs' linkedin-job-search-api
// honours as a single-token `location_filter` value. Each entry is exactly
// what the vendor recognises — no comma compositions, no country-code suffixes.
// Covers: every country we support + every major tech-hub city globally.
// Users pick from this list via datalist so we never send a malformed filter.

export const LINKEDIN_LOCATIONS: readonly string[] = [
  // Remote
  "Remote",

  // Countries
  "United Kingdom",
  "United States",
  "Germany",
  "France",
  "Netherlands",
  "Ireland",
  "Spain",
  "Italy",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Portugal",
  "Switzerland",
  "Austria",
  "Belgium",
  "Czech Republic",
  "Romania",
  "Estonia",
  "Lithuania",
  "Latvia",
  "Canada",
  "Australia",
  "New Zealand",
  "Singapore",
  "Japan",
  "India",
  "Brazil",
  "Mexico",
  "Israel",
  "United Arab Emirates",

  // UK cities
  "London",
  "Manchester",
  "Birmingham",
  "Edinburgh",
  "Glasgow",
  "Bristol",
  "Cambridge",
  "Oxford",
  "Leeds",
  "Sheffield",
  "Cardiff",
  "Belfast",
  "Dublin",
  "Liverpool",
  "Brighton",
  "Reading",

  // US tech hubs
  "New York",
  "San Francisco",
  "Seattle",
  "Austin",
  "Boston",
  "Chicago",
  "Los Angeles",
  "Washington",
  "Denver",
  "Atlanta",
  "San Diego",
  "Portland",
  "Raleigh",
  "Dallas",
  "Miami",

  // Europe tech hubs
  "Berlin",
  "Munich",
  "Hamburg",
  "Frankfurt",
  "Cologne",
  "Amsterdam",
  "Rotterdam",
  "Paris",
  "Lyon",
  "Barcelona",
  "Madrid",
  "Milan",
  "Rome",
  "Stockholm",
  "Oslo",
  "Copenhagen",
  "Helsinki",
  "Zurich",
  "Geneva",
  "Vienna",
  "Brussels",
  "Lisbon",
  "Warsaw",
  "Krakow",
  "Prague",
  "Bucharest",
  "Tallinn",
  "Vilnius",
  "Riga",

  // North America (non-US)
  "Toronto",
  "Vancouver",
  "Montreal",
  "Ottawa",

  // APAC
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Auckland",
  "Wellington",
  "Tokyo",
  "Singapore",
  "Hong Kong",
  "Bangalore",
  "Mumbai",
  "Delhi",
  "Hyderabad",

  // Other
  "Tel Aviv",
  "Dubai",
  "Abu Dhabi",
  "São Paulo",
  "Mexico City",
];
