#!/usr/bin/env bash
# scripts/setup.sh — generate .env with random free ports (stable after first run).
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -f .env ]]; then
  echo ".env already exists; refusing to overwrite. Delete it first if you want to regenerate."
  exit 0
fi

find_free_port() {
  python3 -c "import socket;s=socket.socket();s.bind(('127.0.0.1',0));print(s.getsockname()[1]);s.close()"
}

APP_PORT="$(find_free_port)"
# Ensure APP_PORT and DB_PORT differ.
DB_PORT="$(find_free_port)"
while [[ "$DB_PORT" == "$APP_PORT" ]]; do
  DB_PORT="$(find_free_port)"
done

DB_PASSWORD="$(openssl rand -hex 24)"

cat > .env <<EOF
# Generated by scripts/setup.sh — edit as needed.
APP_PORT=${APP_PORT}
DB_PORT=${DB_PORT}
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgres://rolehunter:${DB_PASSWORD}@db:5432/rolehunter

# Fill these in:
ANTHROPIC_API_KEY=
GEMINI_API_KEY=
JSEARCH_RAPIDAPI_KEY=
LINKEDIN_RAPIDAPI_HOST=linkedin-job-search-api.p.rapidapi.com

DEFAULT_LLM_PROVIDER=claude
CLAUDE_MODEL=claude-sonnet-4-6
GEMINI_MODEL=gemini-2.5-pro
EOF

chmod 600 .env

cat <<EOF
Generated .env:
  App:      http://127.0.0.1:${APP_PORT}
  Postgres: 127.0.0.1:${DB_PORT}
Next steps:
  1. Add your API keys to .env (ANTHROPIC_API_KEY / GEMINI_API_KEY / JSEARCH_RAPIDAPI_KEY).
  2. docker compose up --build -d
  3. docker compose exec app npx drizzle-kit migrate
  4. Open http://127.0.0.1:${APP_PORT}
EOF
